server:
  port: 4003

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT --> http://localhost:4004/auth/login
        ## API GATEWAY --> http://auth-service:4004/login
        - id: auth-service-route
          uri: http://host.docker.internal:4004
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        ## REST CLIENT --> http://localhost:4003/api/patients
        ## API GATEWAY --> http://patient-service:4000
        ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients Array
        - id: patient-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation
        ## REST CLIENT --> http://localhost:4003/api-docs/patients
        ## API GATEWAY --> http://patient-service:4000/v3/api-docs
        ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients Array
        - id: api-docs-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath= /api-docs/patients,/v3/api-docs
        ## REST CLIENT --> http://localhost:4003/api-docs/auth
        ## API GATEWAY --> http://auth-service:4004/v3/api-docs
        ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients Array
        - id: api-docs-auth-route
          uri: http://host.docker.internal:4004
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath= /api-docs/auth,/v3/api-docs