### POST request to create a new patient that is invalid: email will be empty
POST http://localhost:4000/patients
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Dough",
  "dateOfBirth": "1234-08-24",
  "address": "7352 Bear Hill Lane, Avon Lake, OH 44012",
  "email": "",
  "phone": "123-456-7890",
  "registerDate": "2025-04-14"
}

###