### POST request to create a new patient
### no longer http://localhost:4000/patients due to using an api gateway
POST http://localhost:4003/api/patients
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Dough",
  "dateOfBirth": "1234-08-24",
  "address": "7352 Bear Hill Lane, Avon Lake, OH 44012",
  "email": "Johnny.Dough@example.com",
  "phone": "123-456-7890",
  "registerDate": "2025-04-14"
}

###